export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SELECT_ADDRESS = 'SELECT_ADDRESS';
export const SELECT_CARD = 'SELECT_CARD';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const UPDATE_ITEM_AMOUNT_ON_CART = 'UPDATE_ITEM_AMOUNT_ON_CART';

export const CREATE_PURCHASE = 'CREATE_PURCHASE';

export const SELECT_FILTER = 'SELECT_FILTER';


